// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DbEntities))]
    [Migration("20171101100232_mymijlkg")]
    partial class mymijlkg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayer.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Academic_Year");

                    b.Property<string>("App_Status");

                    b.Property<int>("BatchInchargeId");

                    b.Property<int>("CourseId");

                    b.Property<string>("Del_Status");

                    b.Property<string>("Description");

                    b.Property<int>("Duration");

                    b.Property<string>("DurationType");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("PatternId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("StartYear");

                    b.Property<int>("SubCourseId");

                    b.HasKey("Id");

                    b.ToTable("AcademicYear");
                });

            modelBuilder.Entity("DataAccessLayer.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("App_Status");

                    b.Property<string>("Course_Name");

                    b.Property<string>("Del_Status");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DataAccessLayer.Semister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("App_Status");

                    b.Property<int>("Batch_Id");

                    b.Property<int>("Course_Id");

                    b.Property<string>("Del_Status");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("Semister_Name");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("StartMonth");

                    b.Property<int>("StartYear");

                    b.HasKey("Id");

                    b.ToTable("Semisters");
                });

            modelBuilder.Entity("DataAccessLayer.SubCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseId");

                    b.Property<string>("Description");

                    b.Property<string>("Sub_Course");

                    b.HasKey("Id");

                    b.ToTable("SubCourses");
                });

            modelBuilder.Entity("DataAccessLayer.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
